### ISSUE TITLE
TIMVISION su OSMC Vero 4K

### ISSUE THREAD

**Issue by target5** [pinoelefante/plugin.video.timvision#13]
Ciao Giuseppe,

innanzitutto ti faccio i miei complimenti per l'add-on che hai sviluppato che è grandioso. Io lo uso su Raspberry PI3 model B e OSMC Kodi. Ho acquistato recentemente da OSMC il Vero 4K che ha Linux a 64 bit e il tuo add-on dopo averlo istallato e caricato si apre regolarmente ma quando lancio la visione di un film non succede niente, come si può risolvere?
Grazie anticipatamente per la risposta.

Cordiali saluti,
Alex

**Comment by rickyproge** [comment]
Ciao,
penso di aver lo stesso problema di Alex, utilizzo OSMC su un rp3 e da quando è collegato ad un televisore 4K non apre i film dandomi un errore del plugin.
Inoltre non trovo i log dai files di OSMC, dove vengono salvati?

Grazie
Riccardo

**Comment by pinoelefante** [comment]
@target5 scusa se non ho risposto prima, ma mi è proprio sfuggita la notifica. Comunque, leggendo sul forum di Kodi mi sembra di capire che il tuo problema sia stato risolto

@rickyproge Non ho capito. Prima di collegarlo alla tv 4k la riproduzione funzionava?
Non uso e non ho mai usato OSMC, ma il file di log dovrebbe trovarsi in questo percorso: ~/.kodi/kodi.log oppure ~/.kodi/tmp/kodi.log
