### ISSUE TITLE
Can't access movies genres folder

### ISSUE THREAD

**Issue by dragonfly-lover** [pinoelefante/plugin.video.timvision#14]
when browsing genres menu (under "movies"), the addon doesn't display cathegories folders. to be clear it doesn't display anything.
(in pratica, quando entri nel menu "Cinema" -> "generi" non visualizza nulla).

All other menus and submenus work correctly.

Tested on Libreelec (8.2.5) for raspy2/3 and kodi 17.5 for ubuntu linux, addon version 1.0.23 (and some others before).

**Comment by pinoelefante** [comment]
Qui si può scrivere in italiano dato che non si deve rispettare il regolamento del forum. Comunque ho provato su Kodi 18 e funziona. Dopo provo su Kodi 17.
Se potessi mandarmi il file di log sarebbe cosa gradita

**Comment by pinoelefante** [comment]
sembra risolto. fammi sapere se ci sono ulteriori problemi
