### ISSUE TITLE
[Requests] Aggiungere "muro semplice" alle modalità di visualizzazione della cartella "Generi"

### ISSUE THREAD

**Issue by dragonfly-lover** [pinoelefante/plugin.video.timvision#15]
La cartella generi può essere visualizzata solo come "muro di icone" o "lista semplice". Tuttavia "muro di icone" carica le immagini della categorie ma lascia molto spazio e le miniature rimangono piccole. Con la modalità "muro semplice" tutto si vedrebbe meglio (più grande e senza spazi morti).

**Comment by pinoelefante** [comment]
Se vuoi abilitarlo, dovresti modificare un file della skin di Kodi. In questo momento non ricordo che tipologia di content venga impostato per i generi
