### ISSUE TITLE
InputStream Adaptive: License update not successful (no keys)

### ISSUE THREAD

**Issue by avalloneandrea** [pinoelefante/plugin.video.timvision#16]
Da alcuni giorni non è più possibile riprodurre i contenuti di Tim Vision su Kodi. Il log mostra questo errore:

`18:08:42.617 T:1343222688   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
18:08:44.080 T:1343222688   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
18:08:44.080 T:1343222688   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
18:08:44.082 T:1343222688   ERROR: CVideoPlayer::OpenInputStream - error opening [https://voddashhttps.cb.ticdn.it/videoteca2/V3/Film/2018/03/50726498/DASH/11429115/11429115_HD_ANSN.mpd]
18:08:44.082 T:1343222688  NOTICE: CVideoPlayer::OnExit()
18:08:44.082 T:1945236032   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.timvision/?action=play_item&contentId=50726498&videoType=MOVIE&has_hd=True&startPoint=0&contentType=MOVIE&duration=6920]
18:08:44.090 T:1945236032  NOTICE: CVideoPlayer::CloseFile()
18:08:44.090 T:1945236032  NOTICE: VideoPlayer: waiting for threads to exit
18:08:44.090 T:1945236032  NOTICE: VideoPlayer: finished waiting
18:08:44.091 T:1945236032  NOTICE: CVideoPlayer::CloseFile()
18:08:44.091 T:1945236032  NOTICE: VideoPlayer: waiting for threads to exit
18:08:44.091 T:1945236032  NOTICE: VideoPlayer: finished waiting
18:09:23.539 T:1945236032   ERROR: GetDirectory - Error getting plugin://plugin.video.timvision/?action=open_page&uri=%2fTRAY%2fEXTCOLLECTION%2f9923%3fdeviceType%3dWEB%26serviceName%3dCUBOVISION
18:09:23.541 T:1945236032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.timvision/?action=open_page&uri=%2fTRAY%2fEXTCOLLECTION%2f9923%3fdeviceType%3dWEB%26serviceName%3dCUBOVISION) failed
18:09:25.206 T:1858073504 WARNING: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.timvision/addon.py): the python script "/storage/.kodi/addons/plugin.video.timvision/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE`

**Comment by avalloneandrea** [comment]
Testato su Raspberry Pi, ma non funziona.

**Comment by colemar** [comment]
Stesso problema su Windows 10 x64 con Kodi 17.6 32-bit.
Ho notato che al primo tentativo di visualizzare qualcosa in TIMVision l'add-on ha scaricato questi
c:\Users\MIONOME\AppData\Roaming\Kodi\cdm\widevinecdm.dll
c:\Users\MIONOME\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\cdm\widevinecdm.dll

Ho verificato la versione del file widevinecdm.dll ed era la 1.4.8.903.
Allora ho chiuso Kodi e sostituito i due file sopra con la versione 1.4.8.970 32-bit che ho trovato non ricordo più dove.
Il problema rimane:
`16:39:10.206 T:4896   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
16:39:10.206 T:4896   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
16:39:10.207 T:4896   ERROR: CVideoPlayer::OpenInputStream - error opening [https://voddashhttps.cb.ticdn.it/videoteca2/V3/Film/2017/08/50685611/DASH/11450477/11450477_HD.mpd]
16:39:10.207 T:4896  NOTICE: CVideoPlayer::OnExit()
16:39:10.210 T:9084   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.timvision/?action=play_item&contentId=50685611&videoType=MOVIE&has_hd=True&startPoint=0&contentType=MOVIE&duration=6684]
`

**Comment by avalloneandrea** [comment]
Sembra che il problema sia con Kodi 17. Aggiornando Kodi alla versione 18 (beta) e sostituendo il file `libwidevinecdm.so` con una versione più aggiornata (io l'ho presa da [qui](url
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_10718.88.2_daisy-spring_recovery_stable-channel_spring-mp-v3.bin.zip)) il plugin funziona di nuovo!

**Comment by pinoelefante** [comment]
@avalloneandrea ottimo. allora chiudo. ho appena visto che sul forum anche altri hanno problemi, ma se mi dici che ora funziona, allora non è legato all'addon

**Comment by pinoelefante** [comment]
@colemar adesso controllo nella mia installazione di kodi se World War Z funziona e ti faccio sapere

**Comment by pinoelefante** [comment]
@colemar cancella il contenuto delle cartella 
c:\Users\MIONOME\AppData\Roaming\Kodi\cdm
e 
C:\Users\MIONOME\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\cdm
e lascia gestire all'addon il download di widevine.
ed ho appena notato che dici Kodi 17.6. Come riportato anche da @avalloneandrea sembra che ci siano problemi sulla versione 17. Ti consiglio di passare a Kodi 18

**Comment by pinoelefante** [comment]
@colemar l'addon simula il comportamento di un browser. il meglio di la7 non si vede nemmeno lì (così come eurosport)
