### ISSUE TITLE
Sottotitoli non più selezionabili

### ISSUE THREAD

**Issue by jackzipper** [pinoelefante/plugin.video.timvision#17]
Buondì, intanto ti ringrazio per questo spettacolare addon, in quanto su fire stick è l'unica alternativa valida all'inesistente app ufficiale.
Volevo segnalare che non viene più indicata la presenza di sottotitoli integrati ai flussi video, l'audio rimane selezionabile (ita, eng), i sottotitoli non vengono elencati (ho preventivamente verificato che effettivamente fossero presenti, per i contenuti selezionati, dei sottotitoli, sul'interfaccia web via pc).
Precedentemente tutto funzionava correttamente, quindi presumo debba essere sopraggiunta qualche modifica nelle API di Timvision...
Ringraziandoti ancora, ti auguro una buona giornata.

**Comment by pinoelefante** [comment]
C'è un piccolo problema. In questi giorni sono passato a fastweb e non so se l'abbonamento a timvision sia ancora attivo. Nel caso, se potessi fornirmi un paio di titoli che dovrebbero avere i sottotitoli mi faresti un piacere

**Comment by jackzipper** [comment]
Grazie per la tempestiva risposta!
Ti elenco alcuni esempi:
Tutte le puntate della serie The Handmaid's Tale hanno i sottotitoli in italiano ed inglese
Tutte le puntate della serie The Magicians  hanno i sottotitoli in italiano ed inglese
Tutte le puntate della serie The Good Fight hanno i sottotitoli in italiano ed inglese

**Comment by pinoelefante** [comment]
Ho controllato. Il manifest che timvision fornisce contiene i sottotitoli. Probabilmente c'è qualche problema con inputstream.adaptive. Provo a chiedere allo sviluppatore

**Comment by jackzipper** [comment]
Credi siano problemi legati al parsing dei TTML?

https://github.com/peak3d/inputstream.adaptive/commit/61397dfa2784a118f8cb019ae06f51e163669392

Ho scaricato un paio di sottotitoli e sembrano ben formattati, per quanto non sono un esperto del formato, allego un paio di esempi che sono riuscito ad estrapolare:
[CMAP00141326_good_fight_S01_EP01_HD_DA_SUB_H264_eng.ttml.txt](https://github.com/pinoelefante/plugin.video.timvision/files/2441089/CMAP00141326_good_fight_S01_EP01_HD_DA_SUB_H264_eng.ttml.txt)
[CMAP00141326_good_fight_S01_EP01_HD_DA_SUB_H264_ita.ttml.txt](https://github.com/pinoelefante/plugin.video.timvision/files/2441090/CMAP00141326_good_fight_S01_EP01_HD_DA_SUB_H264_ita.ttml.txt)

**Comment by pinoelefante** [comment]
@jackzipper mi potresti dire se ci sono cambiamenti con la nightly di oggi?

**Comment by jackzipper** [comment]
Provata ora la versione kodi-20181104-4419febe-master-armeabi-v7a.apk, ancora niente sottotitoli
