### ISSUE TITLE
Pallino che gira ma non si vede

### ISSUE THREAD

**Issue by mikysal78** [pinoelefante/plugin.video.timvision#18]
Ho provato a reinstallare da zero osmc su una RaspBerry P3 B+ ma non va.
root@osmc:~# more /etc/os-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="August 2018"
VERSION_ID="2018.08-2"
ID=osmc
ID_LIKE=debian

Dando un tail -f ho questo
https://pastebin.com/8XLMzyrc

con un grab-logs -A ho questo
https://paste.osmc.tv/uxopibomoc

Cosa si può fare?

**Comment by pinoelefante** [comment]
Starting Kodi (17.6)
Kodi 17 non è più supportato

**Comment by pinoelefante** [comment]
@mikysal78 adesso funziona?
