### ISSUE TITLE
Ogni 10 minuti i film si bloccano

### ISSUE THREAD

**Issue by fabri2** [pinoelefante/plugin.video.timvision#20]
Sto provando l'addon Timvision su "wonderbox.tv 18.0 alpha 1" installato su tv box android 6 (tx5 pro) ma ogni film si freeza ogni 10 minuti circa (l'audio va avanti ma l'immagine é freezata).
Dipende dal "keep alive"?

**Comment by pinoelefante** [comment]
riavvia il tuo dispositivo e riprova

**Comment by pinoelefante** [comment]
potrebbe dipendere da questo bug: https://github.com/pinoelefante/plugin.video.timvision/issues/9

**Comment by fabri2** [comment]
Ho appena riprovato l'addon dopo aver spento x tutta la notte il box.
Il film si é bloccato dopo 4 minuti (fermo immagine + audio che continua normalmente).
Se si tratta del bug che dici si può rimediare?
Ah, grazie per il tuo lavoro :)

**Comment by pinoelefante** [comment]
se si ferma dopo 4 minuti no. e non avevo notato che l'audio continua a funzionare.
per prima cosa prova ad aggiornare kodi all'ultima beta disponibile. vedere un log (con la modalità debug di kodi attivata) potrebbe aiutare

**Comment by fabri2** [comment]
Ho aggiornato kodi alla vers 18 beta3
Il blocco del film su timvision si è verificato dopo 20 minuti.
Proverò dopo anche con la modalità debug di kodi attivata ma mi sto convincendo sempre più che il problema risiede nei server tim

PS
Su kodi 18 beta 3 l'addon SOD pureita non funziona :(

**Comment by fabri2** [comment]
Stasera  il film su timvision si é bloccato dopo circa 23 min. Ti allego il log
[kodi.log.zip](https://github.com/pinoelefante/plugin.video.timvision/files/2484649/kodi.log.zip)

**Comment by pinoelefante** [comment]
Se ti colleghi in WiFi, prova con il cavo

**Comment by fabri2** [comment]
Ho connesso via ethernet il box al modem hub (... una specie di trasloco). Un film di 90 minuti NON si é bloccato. Giuseppe mó questa me la spieghi :)

**Comment by pinoelefante** [comment]
certo. se vedi nel log c'è questa riga:

> CCurlFile::FillBuffer - Failed: Timeout was reached(28)

in pratica è come se il box si fosse disconnesso dalla rete per qualche momento o comunque ci fosse un problema di rete.
potrebbe anche essere che con il tuo dispositivo principale non ci saranno problemi.

fai anche qualche altro test e fammi sapere :D

**Comment by fabri2** [comment]
Allora il problema dovrebbe presentarsi anche con lo streaming da altri canali ma in realtà non é mai successo.

**Comment by fabri2** [comment]
NON è colpa del tuo addon ma del mio box tv che sporadicamente e solo con timvision si sconnette dalla rete wifi. Non è servito formattarlo e l'update del firmware (originale),
Sto usando attualmente un box tv gemello che avevo già e non ho più problemi di rete con timvision.
Grazie di tutto Giuseppe ;)
