### ISSUE TITLE
No video - Ok Catalogo (Windows 10)

### ISSUE THREAD

**Issue by myidforgit** [pinoelefante/plugin.video.timvision#21]
Ciao,
non riesco più ad usare tim vision, ho disinstallato cancellayo anche dati utente, ri installato, montato KODI mod e Tim vision da tuo repository ma non va. Si riesce a navigare nel menù ma non a vedere.
Ho allegato File.

[kodi.log](https://github.com/pinoelefante/plugin.video.timvision/files/2523021/kodi.log)

Grazie

**Comment by pinoelefante** [comment]
funziona solo su kodi 18
