### ISSUE TITLE
Serie TV visibili solo in SD

### ISSUE THREAD

**Issue by frasty** [pinoelefante/plugin.video.timvision#22]
Da qualche settimana le serie TV sono visibili soltanto in SD mentre gli altri contenuti continuano ad essere fruibili in FHD. Può essere cambiato qualcosa lato DRM?
Uso Kodi 18rc5

**Comment by pinoelefante** [comment]
Non so risponderti. Non sto seguendo più lo sviluppo né dell'addon né di Kodi e la parte DRM

**Comment by gustavodandolo** [comment]
Salve, non c'è la possibilità di reperire versioni più vecchie dell'addon giusto per provare?

**Comment by gustavodandolo** [comment]
Hai ragione, scusami, non ci avevo fatto caso, grazie.

**Comment by pinoelefante** [comment]
oggi ho attivato una versione di prova e vi farò sapere
