### ISSUE TITLE
kodi v19

### ISSUE THREAD

**Issue by dga4130-renato** [pinoelefante/plugin.video.timvision#26]
Ciao,
volevo chiederti se era possibile aggiornare l'addon x kodi v 19
in quanto questa versione usa python 3 e l'addon non funziona.
grazie.
https://forum.kodi.tv/showthread.php?tid=343068

**Comment by pinoelefante** [comment]
Ciao e scusa se rispondo solo ora.
Non avendo più un account su timvision non potrei testare il reale funzionamento dell'addon

**Comment by GlawenClattuck** [comment]
Ciao
con il miglioramento sensibile di TimVsion piacerebbe anche a me usarlo su Kodi. Come potevo immaginare su Kodi 19 non va, ma ahimè non va neanche con la versione Kodi 18.8 che è la più recente.
Se ti serve un beta tester per fare le prove, le faccio io con il mio account...

**Comment by unecc** [comment]
ciao funziona con kodi v20? Sarebbe perfetto

**Comment by unecc** [comment]
nessuno? Progetto abbandonato?
