### ISSUE TITLE
[Player] Disconnessione dopo circa un'ora

### ISSUE THREAD

**Issue by pinoelefante** [pinoelefante/plugin.video.timvision#7]
@pippocalo
> il problema capita nella normale riproduzione di video dal sito TIMVISION; la mia sensazione è come se TIMVISION ogni tanto (circa ogni ora o poco meno) verifichi la autorizzazione e non la trovi bloccando la visione

**Comment by pinoelefante** [comment]
Possiamo provare a mandare richieste KeepAlive ogni X minuti mentre è in riproduzione

**Comment by pinoelefante** [comment]
Ho guardato un po' le richieste del player di timvision e sembra che le richieste di keep alive debbano essere mandate ogni 10 minuti

**Comment by axlt2002** [comment]
Grazie pinoelefante! Io personalmente non ho avuto  modo di verificare, ma credo proprio sia un problema di "keep alive".

Resto in attesa della nuova versione per fare una prova consistente.

Ciao e grazie,

Alex
